# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Python, GitHub Actions, and Azure App Service: https://aka.ms/python-webapps-actions

name: Build and deploy Python app to Azure Web App - tradingviewforwarder

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate
          
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Build frontend
        run: |
          cd frontend
          npm ci
          npm run build
          cd ..
          
      - name: List static directory contents
        run: |
          echo "Static directory contents:"
          if [ -d "static" ]; then
            ls -la static
          else
            echo "Static directory not found!"
          fi
      
      # CRITICAL: Delete any existing output.tar.gz files to prevent issues
      - name: Remove any tar.gz files
        run: |
          echo "Removing any existing tar.gz files to prevent deployment issues"
          find . -name "*.tar.gz" -delete
          find . -name "output.tar.gz" -delete
          
          # Verify no tar.gz files exist
          echo "Checking for any remaining tar.gz files:"
          find . -name "*.tar.gz" || echo "No tar.gz files found"
      
      - name: Install dependencies
        run: pip install -r requirements.txt
        
      - name: Verify application
        run: |
          # Run a basic check to make sure the app imports correctly
          python -c "import main; print('Application imports successfully')"
          # Create a test file marker
          echo "Application verification passed" > verification_passed.txt

      - name: Prepare deployment files
        run: |
          # Create a minimal .env file for production
          echo "DEBUG=False" > .env
          echo "CORS_ORIGIN=*" >> .env
          
          # Create Azure deployment markers
          echo "App deployment timestamp: $(date)" > azure_deploy_marker.txt
          echo "App deployed from GitHub Actions" >> azure_deploy_marker.txt
          
          # Create marker to indicate no tar.gz is used
          echo "NO_TARGZ_DEPLOYMENT=true" > no_targz_deployment.txt
          echo "This deployment does not use output.tar.gz" >> no_targz_deployment.txt
          echo "Static files are copied directly" >> no_targz_deployment.txt
          echo "Deployment timestamp: $(date)" >> no_targz_deployment.txt
          
          # Ensure web.config exists
          if [ ! -f "web.config" ]; then
            echo "web.config not found, creating default!"
            echo '<?xml version="1.0" encoding="UTF-8"?>' > web.config
            echo '<configuration>' >> web.config
            echo '  <system.webServer>' >> web.config
            echo '    <handlers>' >> web.config
            echo '      <add name="httpPlatformHandler" path="*" verb="*" modules="httpPlatformHandler" resourceType="Unspecified" />' >> web.config
            echo '    </handlers>' >> web.config
            echo '    <httpPlatform processPath="python"' >> web.config
            echo '                  arguments="-m gunicorn main:app --bind=0.0.0.0:%HTTP_PLATFORM_PORT% --worker-class=uvicorn.workers.UvicornWorker --timeout 600 --workers 4"' >> web.config
            echo '                  stdoutLogEnabled="true"' >> web.config
            echo '                  stdoutLogFile="\\?\%home%\LogFiles\stdout.log"' >> web.config
            echo '                  startupTimeLimit="300">' >> web.config
            echo '      <environmentVariables>' >> web.config
            echo '        <environmentVariable name="PORT" value="%HTTP_PLATFORM_PORT%" />' >> web.config
            echo '        <environmentVariable name="PYTHONUNBUFFERED" value="1" />' >> web.config
            echo '      </environmentVariables>' >> web.config
            echo '    </httpPlatform>' >> web.config
            echo '  </system.webServer>' >> web.config
            echo '</configuration>' >> web.config
          fi

      - name: Create emergency cleanup script
        run: |
          # Create a script to immediately remove output.tar.gz if found
          echo '#!/bin/bash' > cleanup_targz.sh
          echo 'echo "======= EMERGENCY CLEANUP OF TAR.GZ FILES ======="' >> cleanup_targz.sh
          echo 'if [ -f "output.tar.gz" ]; then' >> cleanup_targz.sh
          echo '  echo "!!! FOUND output.tar.gz - REMOVING IT IMMEDIATELY !!!"' >> cleanup_targz.sh
          echo '  rm -f output.tar.gz' >> cleanup_targz.sh
          echo '  echo "output.tar.gz has been removed"' >> cleanup_targz.sh
          echo 'else' >> cleanup_targz.sh
          echo '  echo "✓ No output.tar.gz found"' >> cleanup_targz.sh
          echo 'fi' >> cleanup_targz.sh
          echo '' >> cleanup_targz.sh
          echo '# Check for any tar.gz files' >> cleanup_targz.sh
          echo 'find . -name "*.tar.gz" > /tmp/targz_files.txt' >> cleanup_targz.sh
          echo 'if [ -s /tmp/targz_files.txt ]; then' >> cleanup_targz.sh
          echo '  echo "!!! WARNING: Found tar.gz files:"' >> cleanup_targz.sh
          echo '  cat /tmp/targz_files.txt' >> cleanup_targz.sh
          echo '  echo "Removing all tar.gz files..."' >> cleanup_targz.sh
          echo '  find . -name "*.tar.gz" -delete' >> cleanup_targz.sh
          echo 'else' >> cleanup_targz.sh
          echo '  echo "✓ No tar.gz files found anywhere"' >> cleanup_targz.sh
          echo 'fi' >> cleanup_targz.sh
          echo 'echo "================================================"' >> cleanup_targz.sh
          chmod +x cleanup_targz.sh
          echo "Created emergency cleanup script"

      - name: Update startup script
        run: |
          # Create a new script with cleanup code at the top
          echo '#!/bin/bash' > startup_new.sh
          echo '' >> startup_new.sh
          echo '# Run emergency cleanup script first' >> startup_new.sh
          echo 'echo "Running emergency cleanup of tar.gz files"' >> startup_new.sh
          echo './cleanup_targz.sh' >> startup_new.sh
          echo '' >> startup_new.sh
          
          # Append the original startup script
          cat startup.sh >> startup_new.sh
          mv startup_new.sh startup.sh
          chmod +x startup.sh
          echo "Updated startup script with cleanup code"

      - name: Prepare deployment package
        run: |
          # Create a clean directory structure for deployment
          mkdir -p app_deploy
          
          # Copy application files
          cp -r *.py *.sh *.json *.txt web.config .env requirements.txt app_deploy/
          cp -r app app_deploy/
          
          # Copy static files directly
          if [ -d "static" ] && [ "$(ls -A static)" ]; then
            mkdir -p app_deploy/static
            cp -r static/* app_deploy/static/
            echo "Static files copied directly to deployment package"
            
            # Create a verification file
            echo "Static files deployed directly at $(date)" > app_deploy/static/direct_deployment.txt
            echo "This deployment does NOT use output.tar.gz" >> app_deploy/static/direct_deployment.txt
            
            # List contents for verification
            echo "Static directory contents:"
            ls -la app_deploy/static/
          else
            echo "No static files to copy, creating placeholder"
            mkdir -p app_deploy/static
            echo '<html><body><h1>App is running</h1><p>No static files were available during deployment.</p></body></html>' > app_deploy/static/index.html
          fi
          
          # Create verification files
          echo "Deployment prepared at $(date)" > app_deploy/deployment_verification.txt
          echo "Files in deployment:" >> app_deploy/deployment_verification.txt
          ls -la app_deploy/ >> app_deploy/deployment_verification.txt
          echo "Static files contents:" >> app_deploy/deployment_verification.txt
          ls -la app_deploy/static/ >> app_deploy/deployment_verification.txt
          
          # CRITICAL CHECK: Make sure no tar.gz files exist in the deployment directory
          echo "Checking for any tar.gz files in deployment directory:"
          find app_deploy -name "*.tar.gz" && echo "ERROR: tar.gz files found in deployment!" || echo "✓ No tar.gz files in deployment"

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: app_deploy
          if-no-files-found: error

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app
          path: app_deploy

      - name: Verify deployment package
        run: |
          echo "Checking deployment package contents:"
          ls -la app_deploy
          
          # Verify static directory
          if [ -d "app_deploy/static" ]; then
            echo "Static directory exists and contains:"
            ls -la app_deploy/static
          else
            echo "ERROR: Static directory is missing!"
          fi
          
          # CRITICAL: Check for any tar.gz files
          echo "Checking for any tar.gz files that might cause issues:"
          find app_deploy -name "*.tar.gz" && echo "ERROR: tar.gz file found!" || echo "✓ No tar.gz files in deployment package"
          
          # Make scripts executable
          chmod +x app_deploy/*.sh

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_F3D169EFBB75465885617AF7F8CD317E }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_D338976C3FD14C438AC7BBAB5BA215A7 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_A59B5AB2EADC48FA812A43C5C5A8BA24 }}

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'tradingviewforwarder'
          slot-name: 'Production'
          package: 'app_deploy'
          timeout-minutes: 15
          respect-slots: true
          max-retries: 3
          retry-wait-seconds: 45

      - name: Verify deployment
        run: |
          echo "Deployment completed at $(date)"
          echo "Waiting 30 seconds for application to start..."
          sleep 30
          echo "You can now access the application at ${{ steps.deploy-to-webapp.outputs.webapp-url }}"
      