# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Python, GitHub Actions, and Azure App Service: https://aka.ms/python-webapps-actions

name: Build and deploy Python app to Azure Web App - tradingviewforwarder

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate
          
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Build frontend
        run: |
          cd frontend
          npm ci
          npm run build
          cd ..
          
      # Create static.tar.gz for easier deployment
      - name: Package static files
        run: |
          if [ -d "static" ]; then
            # Remove previous output.tar.gz if exists
            rm -f output.tar.gz
            # Create the new archive
            tar -czf static.tar.gz -C static .
            mv static.tar.gz output.tar.gz
            echo "Static files packaged successfully"
            ls -la output.tar.gz
          else
            echo "Warning: static directory not found"
            ls -la
          fi
      
      - name: Install dependencies
        run: pip install -r requirements.txt
        
      # Optional: Add step to run tests here (PyTest, Django test suites, etc.)

      - name: Prepare deployment files
        run: |
          # Create a minimal .env file for production
          echo "DEBUG=False" > .env
          echo "CORS_ORIGIN=*" >> .env
          
          # Create empty static dir if it doesn't exist
          mkdir -p static

      - name: Zip artifact for deployment
        run: |
          zip -r release.zip . -x "venv/*" "__pycache__/*" "*.pyc" "*.pyo" "*.pyd" ".git/*" ".github/*" ".vscode/*" "*.log" ".pytest_cache/*" "node_modules/*" "*.db" "frontend/node_modules/*" "static/*" "output.tar.gz"

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: |
            release.zip
            output.tar.gz
            !venv/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Remove any existing output.tar.gz before unzipping
        run: rm -f output.tar.gz || true

      - name: Unzip artifact for deployment
        run: unzip -o release.zip

      - name: Verify deployment files
        run: |
          echo "Listing key deployment files:"
          ls -la web.config*
          ls -la startup.sh
          ls -la deploy.sh
          ls -la main.py
          ls -la output.tar.gz || echo "output.tar.gz not found (this is expected)"
          
          # Ensure scripts are executable
          chmod +x *.sh
          
          # Check for important configuration files
          [ -f "web.config" ] && echo "✅ web.config exists" || echo "❌ web.config missing"
          [ -f "web.config.deploy" ] && echo "✅ web.config.deploy exists" || echo "❌ web.config.deploy missing"
          [ -f "startup.sh" ] && echo "✅ startup.sh exists" || echo "❌ startup.sh missing"
          [ -f "deploy.sh" ] && echo "✅ deploy.sh exists" || echo "❌ deploy.sh missing"

      - name: Run deployment preparation script
        run: |
          chmod +x deploy.sh
          ./deploy.sh
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_F3D169EFBB75465885617AF7F8CD317E }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_D338976C3FD14C438AC7BBAB5BA215A7 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_A59B5AB2EADC48FA812A43C5C5A8BA24 }}

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'tradingviewforwarder'
          slot-name: 'Production'
          timeout-minutes: 15
          respect-slots: true
          max-retries: 3
          retry-wait-seconds: 45
      